### ISSUE TITLE
getContactRecords($crmLookupCriteria) pulls all records and ignores criteria.

### ISSUE THREAD

**Issue by internic99** [kielerrr/Five9#1]
I came here because I couldn't figure out what I was doing wrong. No matter what criteria I put in, the code returns all of the the records in my CRM (well, the first 1000 records). And because I couldn't figure out what 'contactIdField' was supposed to be. Seems like it's nothing.

It looks like my code was fine, and pretty much matched yours, but I still get the same result.

This is my code:

	$crmFieldCriterion = array(
		array(
			'field' => 'number1',
			'value' => '9045551212'
		)
	);
	
	$crmLookupCriteria = array (
		'contactIdField' => '1', 
		'criteria' => $crmFieldCriterion
	); 
	$contactsLookupResult = $five9->getContactRecords($crmLookupCriteria);
	print_r($contactsLookupResult);

**Comment by internic99** [comment]
Nevermind...I got it. I wasn't putting the $crmLookupCriteria into it's own array as a value of the lookupCriteria parameter.

Should be:

$crmFieldCriterion = array(
	array(
		'field' => 'number1',
		'value' => '9045551212'
	)
);

$crmLookupCriteria = array (
	'contactIdField' => '1', 
	'criteria' => $crmFieldCriterion
); 

$lookupCriteria = array(
	'lookupCriteria' => $crmLookupCriteria
);

$contactsLookupResult = $five9->getContactRecords($lookupCriteria);
print_r($contactsLookupResult);

**Comment by internic99** [comment]
Oh, also, I now know what contactIdField is.

You can put any string in there you want, and in the response you get, that string will be the name of the field in which Five9's unique identifier is returned.

So, I named mine "Five9Id"

**Comment by kielerrr** [comment]
@internic99 glad you got it worked out!
